### ISSUE TITLE
Secrets with predefined values are randomized

### ISSUE THREAD

**Issue by sflandergan** [deviceinsight/k8s-secret-provisioner#2]
When defining a password or private key with `secretValue` defined the value should just be base64 encoded into the secret.
Unfortunately the password is still randomized, since the `default` sprig expression is in the wrong order.

Rendering:
```
passwords:
  predefined:
    secretName: predefined
    prefixRelease: false
    secretKey: hello
    secretValue: world
```

Should create the following config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-k8s-secret-provisioner-hook
  labels:
    app: release-name-k8s-secret-provisioner
    chart: k8s-secret-provisioner-${project.version}
    release: release-name
    heritage: Tiller
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed,before-hook-creation
data:
  secrets.yaml: |
    release: release-name
    secrets:
    - identifier:
        namespace: default
        name: predefined
      secrets:
        hello: "d29ybGQ="
```
